dependencies:
- name: bdd-gh-1584665432
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-1584665432
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-nh-import-1584671972
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-sbhg-1584665432
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: bdd-spring-1584663949
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
